CREATE DATABASE prefieromizona DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;


GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON prefieromizona.* TO prefieromizona@localhost IDENTIFIED BY 'prefieromizona';