ALTER TABLE `prefieromizona`.`clientes` 
ADD COLUMN `ID_USUARIO` INT NULL AFTER `TELEFONO`;

ALTER TABLE `prefieromizona`.`comercios` 
ADD COLUMN `ID_USUARIO` INT NULL AFTER `COD_POSTAL`;


-- Table USUARIOS

CREATE TABLE `USUARIOS`
(
  `ID_USUARIO` Int NOT NULL,
  `LOGIN` Varchar(20) NOT NULL,
  `PASSWORD` Varchar(20) NOT NULL,
  `CAMBIAR_PASSWORD` Varchar(1)
)
;

ALTER TABLE `USUARIOS` ADD PRIMARY KEY (`ID_USUARIO`)
;

-- Table ROLES

CREATE TABLE `ROLES`
(
  `ID_ROL` Int NOT NULL,
  `NOMBRE_ROL` Varchar(20)
)
;

ALTER TABLE `ROLES` ADD PRIMARY KEY (`ID_ROL`)
;

-- Table ROLES_USUARIOS

CREATE TABLE `ROLES_USUARIOS`
(
  `ID_USUARIO` Int NOT NULL,
  `ID_ROL` Int NOT NULL
)
;

ALTER TABLE `ROLES_USUARIOS` ADD PRIMARY KEY (`ID_USUARIO`,`ID_ROL`)
;

-- Create foreign keys (relationships) section ------------------------------------------------- 


ALTER TABLE `ROLES_USUARIOS` ADD CONSTRAINT `FK_ROLS_USU_USUARIOS` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `ROLES_USUARIOS` ADD CONSTRAINT `FK_ROLS_USU_ROLES` FOREIGN KEY (`ID_ROL`) REFERENCES `ROLES` (`ID_ROL`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `CLIENTES` ADD CONSTRAINT `FK_CLIENTES_USUARIOS` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `COMERCIOS` ADD CONSTRAINT `FK_COMERCIOS_USUARIOS` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


